In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier



In [2]:
df=pd.read_csv('data/card_transdata.csv')
df.head()

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
0,57.877857,0.311140,1.945940,1.0,1.0,0.0,0.0,0.0
1,10.829943,0.175592,1.294219,1.0,0.0,0.0,0.0,0.0
2,5.091079,0.805153,0.427715,1.0,0.0,0.0,1.0,0.0
3,2.247564,5.600044,0.362663,1.0,1.0,0.0,1.0,0.0
4,44.190936,0.566486,2.222767,1.0,1.0,0.0,1.0,0.0


In [3]:
df['fraud'].unique()


array([0., 1.])

In [4]:
y=df['fraud']
x=df.drop('fraud',axis=1)

In [5]:
len(df)


1000000

In [6]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,train_size=0.9)


In [7]:
log=LogisticRegression()
model=log.fit(x_train,y_train)
model.score(x_test,y_test)

c:\Users\hp\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.95866

In [8]:
df['fraud'].value_counts()


fraud
0.0    912597
1.0     87403
Name: count, dtype: int64

In [9]:
y_pred=model.predict(x_test)


In [10]:
confusion_matrix(y_test,y_pred)


array([[90664,   633],
       [ 3501,  5202]], dtype=int64)

In [11]:
tree=DecisionTreeClassifier()
model_tree=tree.fit(x_train,y_train)
model_tree.score(x_test,y_test)

1.0

In [12]:
y_tree_pred=model_tree.predict(x_test)


In [13]:
confusion_matrix(y_test,y_tree_pred)


array([[91297,     0],
       [    0,  8703]], dtype=int64)

In [14]:
a=pd.DataFrame()
a['true']=y_test
a['pred']=y_pred

In [15]:
a[a['true']==1].value_counts()


true  pred
1.0   1.0     5202
      0.0     3501
Name: count, dtype: int64